# myweb_uwsgi.ini file
[uwsgi]

# Django-related settings
project = EasyTesting
base = /var/www/html


chdir = %(base)/%(project)
module = %(project).wsgi:application


master = true
processes = 4


socket = %(base)/%(project)/%(project).sock
chmod-socket = 666
vacuum = true
buffer-size = 655360