# Generated by Django 4.2.11 on 2026-02-10 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="配置名称", max_length=100, verbose_name="配置名称"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="是否激活", default=False, verbose_name="是否激活"
                    ),
                ),
                (
                    "email_backend",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "SendGrid API"),
                            ("mailgun", "Mailgun API"),
                        ],
                        db_comment="邮件后端",
                        default="smtp",
                        max_length=20,
                        verbose_name="邮件后端",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        db_comment="SMTP 服务器",
                        max_length=255,
                        verbose_name="SMTP 服务器",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True,
                        db_comment="SMTP 端口",
                        default=587,
                        null=True,
                        verbose_name="SMTP 端口",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        db_comment="SMTP 用户名",
                        max_length=255,
                        verbose_name="SMTP 用户名",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        db_comment="SMTP 密码",
                        max_length=255,
                        verbose_name="SMTP 密码",
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(
                        db_comment="使用 TLS", default=True, verbose_name="使用 TLS"
                    ),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(
                        db_comment="使用 SSL", default=False, verbose_name="使用 SSL"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        db_comment="API 密钥",
                        max_length=255,
                        verbose_name="API 密钥",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        db_comment="默认发件人邮箱", max_length=254, verbose_name="默认发件人邮箱"
                    ),
                ),
                (
                    "default_from_name",
                    models.CharField(
                        db_comment="默认发件人名称", max_length=100, verbose_name="默认发件人名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件配置",
                "verbose_name_plural": "邮件配置",
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="环境名称", max_length=100, verbose_name="环境名称"
                    ),
                ),
                ("base_url", models.URLField(db_comment="环境URL", verbose_name="环境URL")),
                (
                    "variables",
                    models.JSONField(
                        blank=True, db_comment="环境变量", default=dict, verbose_name="环境变量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "环境",
                "verbose_name_plural": "环境",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="项目名称", max_length=100, verbose_name="项目名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="项目描述", verbose_name="项目描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="任务名称", max_length=200, verbose_name="任务名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="任务描述", verbose_name="任务描述"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "单次执行"),
                            ("daily", "每日执行"),
                            ("weekly", "每周执行"),
                            ("monthly", "每月执行"),
                            ("cron", "Cron表达式"),
                        ],
                        db_comment="调度类型",
                        default="daily",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        db_comment="Cron表达式",
                        help_text="仅当调度类型为Cron时使用",
                        max_length=100,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True,
                        db_comment="执行时间",
                        help_text="每日/每周/每月执行的具体时间",
                        null=True,
                        verbose_name="执行时间",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True,
                        db_comment="执行日期",
                        help_text="单次执行的日期",
                        null=True,
                        verbose_name="执行日期",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        db_comment="星期几",
                        help_text="每周执行时的星期几(1-7)",
                        null=True,
                        verbose_name="星期几",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        db_comment="每月第几天",
                        help_text="每月执行时的日期(1-31)",
                        null=True,
                        verbose_name="每月第几天",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "激活"),
                            ("inactive", "停用"),
                            ("paused", "暂停"),
                        ],
                        db_comment="任务状态",
                        default="active",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "send_email_notification",
                    models.BooleanField(
                        db_comment="发送邮件通知", default=True, verbose_name="发送邮件通知"
                    ),
                ),
                (
                    "notification_emails",
                    models.TextField(
                        blank=True,
                        db_comment="通知邮箱",
                        help_text="多个邮箱用逗号分隔",
                        verbose_name="通知邮箱",
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(
                        db_comment="成功时通知", default=False, verbose_name="成功时通知"
                    ),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(
                        db_comment="失败时通知", default=True, verbose_name="失败时通知"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        db_comment="最大重试次数", default=3, verbose_name="最大重试次数"
                    ),
                ),
                (
                    "retry_delay",
                    models.IntegerField(
                        db_comment="重试间隔(秒)", default=300, verbose_name="重试间隔(秒)"
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="上次执行时间",
                        null=True,
                        verbose_name="上次执行时间",
                    ),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="下次执行时间",
                        null=True,
                        verbose_name="下次执行时间",
                    ),
                ),
                (
                    "total_runs",
                    models.IntegerField(
                        db_comment="总执行次数", default=0, verbose_name="总执行次数"
                    ),
                ),
                (
                    "successful_runs",
                    models.IntegerField(
                        db_comment="成功次数", default=0, verbose_name="成功次数"
                    ),
                ),
                (
                    "failed_runs",
                    models.IntegerField(
                        db_comment="失败次数", default=0, verbose_name="失败次数"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_comment="Celery任务ID",
                        max_length=255,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_scheduled_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        db_comment="执行环境",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="test_manager.environment",
                        verbose_name="执行环境",
                    ),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="用例名称", max_length=100, verbose_name="用例名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="用例描述", verbose_name="用例描述"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        db_comment="请求方法",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "request_url",
                    models.CharField(
                        db_comment="请求URL", max_length=500, verbose_name="请求URL"
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        blank=True, db_comment="请求头", default=dict, verbose_name="请求头"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        db_comment="请求体",
                        default=dict,
                        null=True,
                        verbose_name="请求体",
                    ),
                ),
                (
                    "request_body_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("form-data", "Form Data")],
                        db_comment="请求体格式",
                        default="json",
                        max_length=20,
                        verbose_name="请求体格式",
                    ),
                ),
                (
                    "expected_status_code",
                    models.IntegerField(
                        db_comment="期望状态码", default=200, verbose_name="期望状态码"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True, db_comment="验证规则", default=list, verbose_name="验证规则"
                    ),
                ),
                (
                    "extract_params",
                    models.JSONField(
                        blank=True, db_comment="提取参数", default=list, verbose_name="提取参数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "skip_test",
                    models.BooleanField(
                        db_comment="跳过测试", default=False, verbose_name="跳过测试"
                    ),
                ),
                (
                    "times",
                    models.IntegerField(
                        db_comment="执行次数", default=1, verbose_name="执行次数"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
            },
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="套件名称", max_length=100, verbose_name="套件名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="套件描述", verbose_name="套件描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_suites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试套件",
                "verbose_name_plural": "测试套件",
            },
        ),
        migrations.CreateModel(
            name="TestSuiteRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_suite_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suite_runs",
                        to="test_manager.environment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suite_runs",
                        to="test_manager.project",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_suite_runs",
                        to="test_manager.testsuite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSuiteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="分组名称", max_length=100, verbose_name="分组名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_suite_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="父分组",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="test_manager.testsuitegroup",
                        verbose_name="父分组",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suite_groups",
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "套件分组",
                "verbose_name_plural": "套件分组",
                "ordering": ["name"],
                "unique_together": {("name", "project", "parent")},
            },
        ),
        migrations.CreateModel(
            name="TestSuiteCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_suite_cases",
                        to="test_manager.environment",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testcase",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="testsuite",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="套件分组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_suites",
                to="test_manager.testsuitegroup",
                verbose_name="套件分组",
            ),
        ),
        migrations.AddField(
            model_name="testsuite",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_suites",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="testsuite",
            name="test_cases",
            field=models.ManyToManyField(
                db_comment="关联用例",
                through="test_manager.TestSuiteCase",
                to="test_manager.testcase",
                verbose_name="关联用例",
            ),
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="运行名称", max_length=100, verbose_name="运行名称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_comment="运行状态",
                        default="pending",
                        max_length=20,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, db_comment="开始时间", null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, db_comment="结束时间", null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        db_comment="运行环境",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.environment",
                        verbose_name="运行环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试套件",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.testsuite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试运行",
                "verbose_name_plural": "测试运行",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        db_comment="运行状态",
                        max_length=20,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, db_comment="响应时间", null=True, verbose_name="响应时间"
                    ),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True, db_comment="响应状态码", null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True, db_comment="响应头", default=dict, verbose_name="响应头"
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        db_comment="响应体",
                        default=dict,
                        null=True,
                        verbose_name="响应体",
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        blank=True, db_comment="请求头", default=dict, verbose_name="请求头"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        db_comment="请求体",
                        default=dict,
                        null=True,
                        verbose_name="请求体",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, db_comment="错误信息", verbose_name="错误信息"
                    ),
                ),
                (
                    "extracted_params",
                    models.JSONField(
                        blank=True, db_comment="提取参数", default=dict, verbose_name="提取参数"
                    ),
                ),
                (
                    "validators",
                    models.JSONField(
                        blank=True, db_comment="验证器", default=list, verbose_name="验证器"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "skip_reason",
                    models.TextField(
                        blank=True, db_comment="跳过原因", verbose_name="跳过原因"
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        db_comment="运行环境",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="test_manager.environment",
                        verbose_name="运行环境",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        db_comment="测试用例",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="test_manager.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        db_comment="测试运行",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="test_manager.testrun",
                        verbose_name="测试运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="报告名称", max_length=255, verbose_name="报告名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="报告描述", null=True, verbose_name="报告描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("test_run", "Test Run"),
                            ("test_suite_run", "Test Suite Run"),
                            ("custom", "Custom"),
                        ],
                        db_comment="报告类型",
                        default="test_run",
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("html", "HTML"), ("pdf", "PDF"), ("json", "JSON")],
                        db_comment="报告格式",
                        default="html",
                        max_length=10,
                        verbose_name="报告格式",
                    ),
                ),
                ("content", models.TextField(db_comment="报告内容", verbose_name="报告内容")),
                (
                    "is_public",
                    models.BooleanField(
                        db_comment="公开", default=False, verbose_name="公开"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建者",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_reports",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "test_results",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试结果",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="test_manager.testresult",
                        verbose_name="测试结果",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试运行",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="test_manager.testrun",
                        verbose_name="测试运行",
                    ),
                ),
                (
                    "test_suite_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试套件运行",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="test_manager.testsuiterun",
                        verbose_name="测试套件运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="分组名称", max_length=100, verbose_name="分组名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_case_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="父分组",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="test_manager.testcasegroup",
                        verbose_name="父分组",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_groups",
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例分组",
                "verbose_name_plural": "用例分组",
                "ordering": ["name"],
                "unique_together": {("name", "project", "parent")},
            },
        ),
        migrations.AddField(
            model_name="testcase",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="用例分组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="test_manager.testcasegroup",
                verbose_name="用例分组",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                        ],
                        db_comment="执行状态",
                        default="running",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="开始时间", verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, db_comment="结束时间", null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        db_comment="执行时长(秒)",
                        null=True,
                        verbose_name="执行时长(秒)",
                    ),
                ),
                (
                    "total_test_cases",
                    models.IntegerField(
                        db_comment="总测试用例数", default=0, verbose_name="总测试用例数"
                    ),
                ),
                (
                    "passed_test_cases",
                    models.IntegerField(
                        db_comment="通过用例数", default=0, verbose_name="通过用例数"
                    ),
                ),
                (
                    "failed_test_cases",
                    models.IntegerField(
                        db_comment="失败用例数", default=0, verbose_name="失败用例数"
                    ),
                ),
                (
                    "error_test_cases",
                    models.IntegerField(
                        db_comment="错误用例数", default=0, verbose_name="错误用例数"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, db_comment="错误信息", verbose_name="错误信息"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        db_comment="重试次数", default=0, verbose_name="重试次数"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        db_comment="邮件已发送", default=False, verbose_name="邮件已发送"
                    ),
                ),
                (
                    "email_sent_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="邮件发送时间",
                        null=True,
                        verbose_name="邮件发送时间",
                    ),
                ),
                (
                    "scheduled_task",
                    models.ForeignKey(
                        db_comment="定时任务",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="test_manager.scheduledtask",
                        verbose_name="定时任务",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试运行",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_execution_logs",
                        to="test_manager.testrun",
                        verbose_name="测试运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行日志",
                "verbose_name_plural": "任务执行日志",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="test_suite",
            field=models.ForeignKey(
                db_comment="测试套件",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to="test_manager.testsuite",
                verbose_name="测试套件",
            ),
        ),
        migrations.CreateModel(
            name="MockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aim",
                    models.CharField(
                        db_comment="用途", max_length=255, verbose_name="用途"
                    ),
                ),
                ("data", models.TextField(db_comment="mock数据", verbose_name="mock数据")),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="数据描述", null=True, verbose_name="数据描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_mock_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟数据",
                "verbose_name_plural": "模拟数据",
            },
        ),
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                db_comment="所属环境",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_comment="访客IP地址", verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        db_comment="浏览器用户代理信息",
                        max_length=500,
                        verbose_name="用户代理",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_comment="访问的URL路径", max_length=500, verbose_name="访问路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        db_comment="HTTP请求方法",
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True,
                        db_comment="来源页面URL",
                        max_length=500,
                        verbose_name="来源页面",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_comment="Django会话KEY",
                        max_length=40,
                        verbose_name="会话KEY",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, db_comment="访问平台", max_length=100, verbose_name="平台"
                    ),
                ),
                (
                    "browser_type",
                    models.CharField(
                        blank=True,
                        db_comment="访问浏览器",
                        max_length=100,
                        verbose_name="浏览器",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="访问时间",
                        db_index=True,
                        verbose_name="访问时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="访问用户（如果已登录）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="访问用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "访客记录",
                "verbose_name_plural": "访客记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="test_manage_created_848550_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="test_manage_ip_addr_018c39_idx"
                    ),
                    models.Index(
                        fields=["user"], name="test_manage_user_id_e1fd78_idx"
                    ),
                ],
            },
        ),
    ]
