# Generated by Django 4.2.7 on 2025-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0002_testcase_request_body_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="request_url",
            field=models.CharField(max_length=500),
        ),
    ]
