# Generated by Django 4.2.7 on 2025-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0003_alter_testcase_request_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("is_active", models.BooleanField(default=False, verbose_name="是否激活")),
                (
                    "email_backend",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "SendGrid API"),
                            ("mailgun", "Mailgun API"),
                        ],
                        default="smtp",
                        max_length=20,
                        verbose_name="邮件后端",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 服务器"
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True, default=587, null=True, verbose_name="SMTP 端口"
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 用户名"
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 密码"
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="使用 TLS"),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(default=False, verbose_name="使用 SSL"),
                ),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=255, verbose_name="API 密钥"),
                ),
                (
                    "default_from_email",
                    models.EmailField(max_length=254, verbose_name="默认发件人邮箱"),
                ),
                (
                    "default_from_name",
                    models.CharField(max_length=100, verbose_name="默认发件人名称"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮件配置",
                "verbose_name_plural": "邮件配置",
            },
        ),
    ]
