# Generated by Django 4.2.11 on 2026-01-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0017_scheduledtask_environment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledtask",
            name="environment",
        ),
    ]
