# Generated by Django 4.2.11 on 2026-01-08 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0019_scheduledtask_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_comment="访客IP地址", verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        db_comment="浏览器用户代理信息",
                        max_length=500,
                        verbose_name="用户代理",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_comment="访问的URL路径", max_length=500, verbose_name="访问路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        db_comment="HTTP请求方法",
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True,
                        db_comment="来源页面URL",
                        max_length=500,
                        verbose_name="来源页面",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_comment="Django会话KEY",
                        max_length=40,
                        verbose_name="会话KEY",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="访问时间",
                        db_index=True,
                        verbose_name="访问时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="访问用户（如果已登录）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="访问用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "访客记录",
                "verbose_name_plural": "访客记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="test_manage_created_848550_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="test_manage_ip_addr_018c39_idx"
                    ),
                    models.Index(
                        fields=["user"], name="test_manage_user_id_e1fd78_idx"
                    ),
                ],
            },
        ),
    ]
