# Generated by Django 4.2.11 on 2026-01-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0020_visitorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorlog",
            name="browser_type",
            field=models.CharField(
                blank=True, db_comment="访问浏览器", max_length=100, verbose_name="浏览器"
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="platform",
            field=models.CharField(
                blank=True, db_comment="访问平台", max_length=100, verbose_name="平台"
            ),
        ),
    ]
