# Generated by Django 4.2.11 on 2026-01-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0021_visitorlog_browser_type_visitorlog_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="skip_test",
            field=models.BooleanField(
                db_comment="跳过测试", default=False, verbose_name="跳过测试"
            ),
        ),
    ]
