# Generated by Django 4.2.11 on 2026-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0022_testcase_skip_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="project",
        ),
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ManyToManyField(
                db_comment="所属环境",
                related_name="environments",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
    ]
