# Generated by Django 4.2.11 on 2026-01-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0023_remove_environment_project_environment_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="project",
        ),
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                db_comment="所属环境",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
            preserve_default=False,
        ),
    ]
