# Generated by Django 4.2.11 on 2026-01-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0024_remove_environment_project_environment_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="skip_reason",
            field=models.TextField(blank=True, db_comment="跳过原因", verbose_name="跳过原因"),
        ),
    ]
