# Generated by Django 4.2.11 on 2026-01-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0025_testresult_skip_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="request_body_code",
            field=models.TextField(
                blank=True,
                help_text="Python代码，用于动态生成请求体",
                null=True,
                verbose_name="请求体代码",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_body_format",
            field=models.CharField(
                choices=[
                    ("json", "JSON"),
                    ("form-data", "Form Data"),
                    ("code", "Python Code"),
                ],
                db_comment="请求体格式",
                default="json",
                max_length=20,
                verbose_name="请求体格式",
            ),
        ),
    ]
