# Generated by Django 4.2.11 on 2026-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0026_testcase_request_body_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="request_body_code",
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_body_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("form-data", "Form Data")],
                db_comment="请求体格式",
                default="json",
                max_length=20,
                verbose_name="请求体格式",
            ),
        ),
    ]
