# Generated by Django 4.2.11 on 2026-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0027_remove_testcase_request_body_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="times",
            field=models.IntegerField(
                db_comment="执行次数", default=1, verbose_name="执行次数"
            ),
        ),
    ]
